# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
    - no_part
    - release/*
    # 表示src目录下任何文件发生改动，触发当前流程
#    paths:
#    - src/*
  pull_request:
    branches: [ main ]
    
  # 每隔一段时间执行一次当前的流程
  schedule:
  - cron: '30 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # 默认安装好了多语言的环境
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          node -v

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  job1:
    runs-on: Ubuntu-latest
    # 指定在什么容器中运行
    container:
      image: node:8
    steps:
      - uses: action/checkout@v2
      - run: |
          node -v

#  build2:
#    need: build